### PR TITLE
Mechanical application of black and isort.

### PR DESCRIPTION
**Pull request by delucchi-cmu**
Also adds a few config lines in `pyproject.toml` for longer lines and black/isort interoperation.

Note that this does NOT address all pylint warnings - there are just fewer.

### CODE REVIEW

**Comment by jeremykubica** [comment]
I don't see the updates to `pyproject.toml`. Should that be included in this PR?

**Comment by grantmerz** [comment]
Can we include the pyproject.toml changes here?  Also, looks like the conflicts are from the PR that moved command line arguments to /utils/.  I can fix those to reflect @jeremykubica's changes

**Comment by delucchi-cmu** [comment]
> I don't see the updates to `pyproject.toml`. Should that be included in this PR?

Good catch - I think I know where those fell off, and it might be best to just start a fresh branch with no conflicts.

**Comment by grantmerz** [comment]
Ok, fresh branch w/out conflicts sounds good

**Pull request closed without merging**
